### PR TITLE
Update makerom for linux, add correct permissions for bannertool, and…

### PR DESCRIPTION
**Pull request by Flat**
… update release build to latest.

### CODE REVIEW

**Comment by Flat** [comment]
Fixes #38 #44 #47 #51

**Comment by 44670** [comment]
sorry, but I could not confirm the binary is trustable or not, where did you get the binary files from?

**Comment by Flat** [comment]
bannertool-linux is the same exact binary just with the executable permission. makerom-linux is from https://github.com/Steveice10/buildtools you can confirm the binary is the same with sha256sum. 
>62c1780660f443e2f03921a8890abdc4254f8c87ccafbad6b47fbc6748fc861c  makerom-linux

**Comment by 44670** [comment]
I see, thanks

**Comment by Margen67** [comment]
>Fixes #38 #44 #47 #51 

tfw issues have been removed

**Pull request merged**
